spring:
  data:
    mongodb:
      host: localhost
      password: password
      username: user
      port: 27017
      database: miniautorizador

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true

vr:
  autorizador:
    cartao:
      saldo-inicial: 500

